### ISSUE TITLE
Latest version always crash when using ConvertBMS

### ISSUE THREAD

**Issue by Airbus480** [zardoru/raindrop#14]
Raindrop crashes when using the ConvertBMS however this does not happen when using version 2.8.0 when I checked in the problem signature this appears:
  Fault Module Name:	MSVCR120.dll

**Comment by zardoru** [comment]
Would you mind handing a file where this issue happens?

**Comment by Airbus480** [comment]
"Would you mind handing a file where this issue happens?" Sorry I didn't get the question but what I can say is that raindrop crashes in every .osu mania maps for example I tried many mania maps especially Maniera or Frozen World and raindrop crashed and no bms generated

**Comment by Dolphinssss** [comment]
Seems like all the separate tools are broken in v0.290/295 (all the batch tools)
It doesn't matter which BMS I feed it, it crashes regardless. I'll try test v0.280 when I am home

**Comment by Airbus480** [comment]
Thanks for the fix when do you plan to release the binary fix?

**Comment by zardoru** [comment]
It's going to take a while, the project's kind of on hold right now. Should be back at full speed on March.
