### ISSUE TITLE
Separating Modes and adding a stylistic swap.

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#20]
One of the main things raindrop suffers from is it's goal to please all.
Whilst I really appreciate the effort it's really hindering the game because players of each game will have their own "perfect" standard.

As a solution to this, I would like to propose that we try to separate each mode as much as possible:
- BMS mode (includes bmson)
  - perhaps add another mode for 9keys (pop mode)?
- Stepmania mode
- O2Jam mode
- osu!mania mode
- potential raindrop mode (for forced raindrop mechanics on all charts)

With this hypothetical solution you would be able to easily shuffle through modes by using one of the function keys (e.g. F3) during song select.
Hitting this key will trigger a stylistic effect that will tell the user what mode they have entered.

Here is a lousy sketch of my interpretation of how the stylistic effect should look: 
![Sketch](http://echo.s-ul.eu/XyytUnSH.png)

Imagine those triangles be some sort of lens flare effect, and that the black bar in the middle will collapse on itself vertically.

By separating the modes this way it will allow people migrating from other games to feel familiar yet be able to easily swap between what they want to play without much hassle.
It also allows much more free room for working on support and mechanics for each format.

I realise this is a rather ambitious request but I truly believe it would be for the better, and it is possible to leave this as an on-going project and implementing it little at a time!

**Comment by zardoru** [comment]
this was technically planned before, but since implementing score and mechanic backends was easier than working on anything else we ended up with this "auto" game mode

**Comment by Dolphinssss** [comment]
Well it is still possible to add the visual aspect of it as it would at the very least create the illusion of separating the modes. (which is good enough, really)

**Comment by zardoru** [comment]
Mhm, that was mostly in progress (in the form of fallback scripts arranged by key mode)

**Comment by zardoru** [comment]
Okay, what we got out there now counts as progress (picking timing mode and gauge). It's not like, _done_ done, but it counts as an update to this issue.

**Comment by Dolphinssss** [comment]
Closing as this is mostly skin-related, and is already a part of the raindrop ARCADE project.
