### ISSUE TITLE
Internet Ranking

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#21]
Don't take this too seriously just yet.

To keep it short: the key to success with any sim is an internet ranking. 

The long version:
Internet ranking being the key to success has been proven over and over in the BMS community:
nazobmplay was the first game to have an IR, it was really popular and people played very competitively and had already reached what were then overjoy charts. 
It stood pretty much uncontested (even with other, nicer-looking players being created) until LRO (LunaticRaveOnline) with its higher quality graphics and its own IR. 
People migrated from nazoIR to LRIR and later on to LR2 with LR2IR. 

You can also see that Bemuse is getting momentum, and one major reason people are interested is because of score tracking and internet ranking, but due to the lack of many features and options LR2 has, Bemuse won't outdo it just yet.

The biggest hurdle in developing an internet ranking would be hosting a server which will cost money (and not just small amounts either!).

anyway as for the features of the IR:
- player profiles - simple overview over various stats and maybe a small self-input description.
- rivals
- score tables
- ghost battles
  - these do not need to be 1-to-1 perfect replays, but a reduced replay like LR2 currently has (where all the notes are autoplayed, but still shows accurate judge)
- peer-to-peer multiplayer (1v1)

**Comment by suitougreentea** [comment]
Perhaps you already know, but apparently Bemuse currently uses Parse, which has 20GB free database storage.
If you implement IR, this service will be helpful in initial stage.

**Comment by zardoru** [comment]
That could be useful, indeed.
What's really scary about this is assuming good faith and trusting client-side data...

**Comment by Dolphinssss** [comment]
There will always be cheaters and people abusing loopholes, so to work against them we would need a moderation team

**Comment by joezeng** [comment]
We'd also need a format where it's easy for humans to spot errors. i.e. if you're going to upload records, upload the replay files to back them up.

**Comment by Dolphinssss** [comment]
Well this idea of IR supports ghost battle which means a reduced replay file similar to how LR2 functions. This is not similar to OSU where only "top 10" or whatever get a very true-to-life replay file saved on the server, but each individual score has one saved. (in case you want to ghost battle against rivals that are not ranked high)

However I don't think replays would suffice as validation as someone would probably be able to edit the replays manually (not sure how LR2IR works but I think it just uploads the score as a replay file and grabs the details from it)

The only viable way (I can think of) would be to let people report scores they consider fake. This puts the effort on the users rather than the moderators, but moderators would still have to review scores case-by-case and decide if they want to terminate an account. (Pretty sure this is how LR2IR works atm, minus the report score system)

**Comment by zardoru** [comment]
The IR system has been separated onto the Chroma-IR project.
Closing as this is not directly relevant to raindrop on its own any more.
