### ISSUE TITLE
bmson - offsync sounds

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#22]
Sometimes a bmson will load with sounds awfully off-sync. I have found this to mostly happen on bmson files where a sound starts on y:0

This happens rather frequently, but not all the time, and usually fixes itself after retrying once.

**Comment by zardoru** [comment]
this bug is inconsistent though and I haven't been able to reproduce it myself.

**Comment by zardoru** [comment]
can you confirm it's still there on 0.300, by the way?

**Comment by Dolphinssss** [comment]
i'll try it tomorrow

**Comment by zardoru** [comment]
I'll assume this was fixed.

**Comment by Dolphinssss** [comment]
reopening due to v0.300 being unable to load bmson right now. (Crazydrift and I discovered this bug and fixed it already)
