### ISSUE TITLE
LR2skin support

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#24]
This is a bit of a stretch (and a somewhat dodgy one too)
Having the ability to import lr2skins would make it very easy for people like me to migrate and use a skin i am comfortable with.

Though I am well aware of the hurdle of this, which is that the only complete documentation of the lr2skin format is in Japanese, with no full translations at this current time. Because of this, the implementation may have to wait.

whilst we're at it why don't we also just add stepmania skin support (i know why osumania wont be supported though)

**Comment by zardoru** [comment]
this is an entire subproject if it were able to happen
stepmania skin support is literally impossible though, we'd pretty much be reimplementing all of stepmania

**Comment by freem** [comment]
Speaking as a StepMania themer for over 10 years, if you value your sanity, you will NOT implement StepMania skin support in Raindrop. :)

**Comment by zardoru** [comment]
beatoraja is a solid alternative if you want a player with lr2 skin support right now.
if someone ever bothers to implement this in lua it could happen, but the engine will, by itself, never support this.
closing.
