### ISSUE TITLE
New Play Options

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#25]
New RANDOM options:
- Mirror
- S-RAN (randomizes each individual note)

New gauges (similar to LR2, IIDX and popn):
- Easy gauge
- Hard Gauge
- EX-Hard gauge
- Hazard (fullcombo) gauge
  These gauge types would apply to clear lamps (see: https://github.com/zardoru/raindrop/issues/18)

Misc. options:
- DP flip (make the sides for DP charts flip)
- Legacy Note (turns all LNs into regular notes, but counts as assist/easy clear)
- Auto-scratch (personally i dont like this but some might want to use it lol)

**Comment by zardoru** [comment]
gauges are in, just need to expose them
mirror is in too, just need to expose it

**Comment by Dolphinssss** [comment]
as per https://github.com/zardoru/raindrop/releases/tag/0.300 most of these are now added. only the miscellaneous options are missing

**Comment by zardoru** [comment]
keeping track of this one elsewhere
