### ISSUE TITLE
Song list sorting

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#26]
The song list is a mess.
I can't even tell what order the songs appear in, but it's not alphabetical and not alphabetically by folder name.

Basically we need options for sorting:
* Sort by Title
* Sort by Level
* Sort by Artist
* Sort by Difficulty
* Sort by Genre (hi pop'n!!)

there are probably other applicable sorting methods but these are the most important ones that come to mind.

**Comment by zardoru** [comment]
genre is so wide open i probably would not seriously consider it.

**Comment by Dolphinssss** [comment]
I didn't really expect you to implement genre sorting anyway
