### ISSUE TITLE
KSH File Format Support

### ISSUE THREAD

**Issue by alexanderkunz** [zardoru/raindrop#35]
Adding support for the .ksh (SDVX) file format would be pretty cool.
We could implement just the buttons A-D and FX and add support for the knobs later.
Two-Dimensional would probably be enough and also be an alternative for the other players with a 3D view.

**Comment by zardoru** [comment]
To be honest - I'd rather not.
I don't like SDVX too much, and the stepmania guys are planning something with respect to it.

**Comment by Dolphinssss** [comment]
added wontfix label for the time being since it's not considered right now

**Comment by zardoru** [comment]
kshoot support is definitely off the road. closing.
