### ISSUE TITLE
Raindrop does not start

### ISSUE THREAD

**Issue by Ovnize** [zardoru/raindrop#43]
![Screenshot of the error](https://cloud.githubusercontent.com/assets/4106415/13729247/b62da49e-e930-11e5-8162-235ba14b2475.png)

**Comment by zardoru** [comment]
Hi.
Please try reinstalling the vs2015 redist files.
https://www.microsoft.com/es-cl/download/details.aspx?id=48145

**Comment by Ovnize** [comment]
It still doesn't work

**Comment by zardoru** [comment]
Did you grab 0.301?
If that still doesn't work, I will have to admit I don't know what the problem is.

**Comment by Ovnize** [comment]
I did. Let's hope that this randomly resolves itself when the next version comes out.
