### ISSUE TITLE
Crash when parsing badly formatted .osu maps

### ISSUE THREAD

**Issue by jerwuqu** [zardoru/raindrop#45]
Example map: https://www.dropbox.com/s/h4k3ah8diqdqyq3/Liz%20Triangle%20-%20primary%20faith%20%28%29%20%5BHard-dance-single%5D.osu?dl=0

**Comment by zardoru** [comment]
Hi, I recently refactored the .osu loader - it doesn't crash when trying to preview this file.
The crash may be on the mp3 loader if you're trying to preview or play it.
Until it's out, you can grab the possibly fixed version (latest debug as this time of writing) from here. https://ci.appveyor.com/api/buildjobs/4c1dmhjt9o1ffgej/artifacts/rd-artifact.zip

If it's not fixed, I'll have to ask for the mp3 file to make sure the crash is not on the mp3 loader.
Thanks!
