### ISSUE TITLE
"Arcade" Mode + Total Reskin Support

### ISSUE THREAD

**Issue by Dolphinssss** [zardoru/raindrop#46]
Personal opinion: I think we should stretch for a proper arcade mode for the game's complete state.

What I mean by this I think we should have a proper game mode similar to DJMAX and IIDX console games, where you play standard mode to get unlocks and eventually reach extra stage etc. Basically make the game look more "commercial" and professional, and also give players a great incentive to keep playing!

Other BMS games that have something similar are "plugout4 ARCADE EDITION" and "endless music for Lunatic Rave".

Not only should one be included with raindrop to begin with, but it should also be possible to completely reconfigure every aspect of this. Everything from unlocks, to missions, to skin and soundset.

Here is a run-down of things we'll need (some may or may not already be supported):
- [ ] Standard Mode
  - Your primary mode where you play a set of songs. Usually 3 or 4 + extra stage. This mode is how you unlock new songs. Song list is specified what stage you're on. E.g. Stage 1 will have a different selection of songs than Stage 2 and 3. Extra Stage is activated if the player meets a specific criteria.
- [ ] Course Mode (aka Expert Mode)
  - Premade courses. Not much to say about this. Courses have their own unique survival gauge which is also used to Dan courses. Courses have their own scoreboard with a total result. 
- [ ] Grade Mode (Dan Courses)
  - A set of courses for keeping track of your skill level. Technically the same as Course Mode.
- [ ] Free Mode
  - Play any of the songs you have unlocked freely. A mode like this might be difficult for raindrop since we also should allow people to play whatever they want which is why I think we should make custom song folders appear in here, or add a second item on the title screen to allow a full free mode (Lite Mode?) without any of the arcade gameplay. 
- [ ] Mission Mode
  - Clear songs or courses with very specific criteria. These are usually unlocked as you clear the missions.
- [ ] Internet Ranking
  - Not really required, but if we want to make the game more attractive we ought to implement it. It will also let us implement the next item on the list.
- [ ] Custom IR support.
  - This idea is taken from endless music. endless music has it's own Internet Ranking powered by Lunatic Rave instead of using the regular Internet Ranking for Lunatic Rave. Free Mode or Lite Mode should disregard this. Currently no ideas for implementation other than IR URL and API key, or something similar.
- [ ] Mode Select screen
  - For obvious reasons. Can this be programmed in via lua?
- [ ] Unlocks
- [ ] Extra Stage

There might be some other interesting features that slipped my mind, or that are too broad.

**Comment by alexanderkunz** [comment]
Very nice ideas. That's the game I would like to play.
But I remember I didn't receive too much positive receptions when I mentioned the arcade style direction in the BMS chat, sadly.
I'd welcome your ideas being implemented, even if it's being done late.

**Comment by Dolphinssss** [comment]
Trust me, I wasn't met with shine and happiness either, but me and Agka talked it out and reached some compromises and decided that even if we're not using all the features for the official game, they'll at least be implemented for others to use.

**Comment by zardoru** [comment]
This is an entire project so closing...
