### ISSUE TITLE
(raindrop 0.400) Terminates while transition to select music

### ISSUE THREAD

**Issue by exch-bms2** [zardoru/raindrop#50]
log.txt:
.
.
.
AUDIO: Requesting latency of 3.000000 ms
AUDIO: Attempting to use shared mode WASAPI
AUDIO: Device Selected 9 (Rate: 48000.000000)
AUDIO: Latency after opening stream = 22.000000ms 
[librocket:4] Loading Lua interpreter
[librocket:4] Loaded font face Togoshi Gothic Regular (from font.ttf).
LuaManager: Running script GameData\Skins\default\mainmenu.lua.
[librocket:3] Unable to open file ScreenMainMenu.rml.
LuaManager: Running script GameData\Skins\default\screenselectmusic.lua.
[librocket:3] Invalid property declaration at :0

**Comment by zardoru** [comment]
It seems unusual that the audio device is using 48kHz - internally raindrop requests 44.1kHz.
Other than that, the other report I had (by JerwuQu) involved a range_error when trying to convert character sets. 

I'm going to look at both cases once I'm able to, since they're the best lead I have.

**Comment by Dolphinssss** [comment]
After someone from Discord tried launching version 0.301, version 0.400 worked fine for him.
Perhaps 0.301 has some files or "does something" that is required for raindrop to run?

**Comment by alexanderkunz** [comment]
I can confirm this bug. It appears to happen when i go to menu and music select several times. Everything seems to work at first though. Also running on default skin, but 44.1kHz.

**Comment by Dolphinssss** [comment]
I am able to execute this error myself: title -> select -> title -> select (crash)

**Comment by zardoru** [comment]
Oh, I thought it was a _different_ instance of crashing, I already knew about the one about leaving select then going in again.

Well then.

**Comment by zardoru** [comment]
after implementing stack logs I was able to definitely confirm that librocket is involved.
librocket seems to attempt to release geometry _twice_. I have no idea if this is because of improper usage or if something's changed in librocket.
Given that this issue is not present on earlier versions of raindrop and the code handling librocket has not changed, but the librocket version has changed, I am pinning it down on librocket.
