### ISSUE TITLE
Where's the program file?

### ISSUE THREAD

**Issue by BurningPower** [zardoru/raindrop#51]
My main goal of using this is to convert .sm files to .osu files.
But apparently i need the file "convertOM.bat", which i can't find anywhere.

Also i can't find the .exe to open raindrop?

[http://puu.sh/pq964/2021ee7928.png]

**Comment by zardoru** [comment]
You downloaded the source code. Look at Code -> Releases for getting the actual executable.

**Comment by BurningPower** [comment]
Thanks alot! Can you hit me for being this blind? xDD
But actually there's an error, either when i try to convert with OM.bat or open RainDrop.exe, an error says that "VCOMP140.DLL" is missing...

**Comment by zardoru** [comment]
Please get this.
https://www.microsoft.com/es-cl/download/details.aspx?id=48145
The x86 version.

**Comment by BurningPower** [comment]
YES! It works now :D thank you so much for your help. I would give you a kiss if i could xD

**Comment by zardoru** [comment]
Closing issue~
