### ISSUE TITLE
issues with using Rate

### ISSUE THREAD

**Issue by Ovnize** [zardoru/raindrop#57]
scrolling speed doesn't scale properly (tested Mode and Constant but I'm pretty sure other speed classes do this too), and the timing windows are affected by the rate

**Comment by zardoru** [comment]
Timing windows being affected by the rate is _technically_ by design.
As for scrolling speed, you'll have to elaborate.

**Comment by Ovnize** [comment]
If I play something using Constant Speed with a target speed of 1400 at x1 and then play it again with the same exact settings except that the rate is now x2, the notes will scroll 2 times faster

**Comment by zardoru** [comment]
I wouldn't exactly consider it an "issue", but I'll definitely change how it works.

**Comment by zardoru** [comment]
the multiplier behaviour on rates has been changed. closing issue.
