### ISSUE TITLE
Crashing while opening the game 

### ISSUE THREAD

**Issue by Reiaa** [zardoru/raindrop#58]
https://b.catgirlsare.sexy/xBwu.png

**Comment by zardoru** [comment]
Hi. There's a known crash when you leave then re-enter song selection.
If this isn't your issue, please post the log. If you can, please try and read the last entry to see if it tried to load a chart - if it did and it wasn't succesful, please post it here.

**Comment by zardoru** [comment]
No follow-up to this crash. I can't help you. Also a duplicate of #50 
closing.
