### ISSUE TITLE
I  can't run the program. Tasukete. :3

### ISSUE THREAD

**Issue by arvinkent098** [zardoru/raindrop#59]
I downloaded most of the missing dll files and I still got this.

http://puu.sh/satTU.jpg

How to solve it? what should I really install? I'm having this kind of pain running and I can't even get a glimpse of the game on my own. :3

**Comment by zardoru** [comment]
please remove all the dlls you got off the internet and get vs 2015 redist x86.
https://www.microsoft.com/en-US/download/details.aspx?id=48145

**Comment by arvinkent098** [comment]
Still no luck :3

http://puu.sh/swJKX/d46557401c.png

log file: http://puu.sh/swJM6/77f311a1a9.log
