### ISSUE TITLE
Make failed in Ubuntu

### ISSUE THREAD

**Issue by xxbidiao** [zardoru/raindrop#66]
Hi, I can't make scons to succeed even when I installed all the dependencies and all the steps followed.
Here is what I got from my console.
```
***@ubuntu:~/Software/raindrop-master$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
clang++ -o src/Application.o -c -std=c++14 -O2 -DNDEBUG -fpermissive -DLINUX -DMP3_ENABLED -Isrc/ext -Isrc -Ilib/include/LuaBridge -Ilib/include/lua -Ilib/include/stb -Ilib/include/stdex -Ilib/include src/Application.cpp
In file included from src/Application.cpp:1:
In file included from src/pch.h:119:
In file included from lib/include/boost/gil/extension/io/png_all.hpp:23:
In file included from lib/include/boost/gil/extension/io/png_write.hpp:24:
In file included from lib/include/boost/gil/extension/io/formats/png/write.hpp:30:
lib/include/boost/gil/extension/io/formats/png/writer_backend.hpp:202:27: error: const_cast from 'value_type *' (aka 'unsigned char *') to 'png_charp' (aka 'char *') is not allowed
                        , const_cast< png_charp >( & (_info._profile.front()) )
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/Application.cpp:1:
src/pch.h:294:20: error: use of undeclared identifier 'a'
                return Fraction{ a / t, b / t };
                                 ^
src/pch.h:294:27: error: use of undeclared identifier 'b'
                return Fraction{ a / t, b / t };

```

What can I do to fix this?

**Comment by mwstobo** [comment]
The fraction errors were fixed in https://github.com/zardoru/raindrop/pull/65 and are in the future branch.

As for the other error, I didn't run into it myself. However, maybe we want a `reinterpret_cast`? I'm not sure.

**Comment by zardoru** [comment]
Huh. That's oddly strict. Converting from unsigned char to signed char not being allowed? Sounds like a good case for reinterpret_cast. 

`& (_info._profile.front())` to `reinterpret_cast<const png_charp>( & (_info._profile.front()) )` 
might be a fix?

Here's more or less that working.
https://ideone.com/4nA2Fj

**Comment by xxbidiao** [comment]
Nice. `future` branch does fixed that problem. However there still seems to be the `writer_backend.hpp` problem. What I'm wondering is that it is coming from the library that should not be having any problems.

What should I do now, to change library code or find a new version?

Edit: Meh, the `future` build just broke the `libjpeg` dependencies and when I added it back it starts complaining the exactly same thing now.

**Comment by zardoru** [comment]
Have you tried the edit I suggested?
